# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 412c08c04c3c21192f17e695303882c56adb43898235bd0f3a8847397ab1e0aeac44c4ed018d5b4ed6af1e80df8d87cc589e3685c62d3d703beca0328f5a5fae

test:
  secret_key_base: 08fe33e2e815f7125031ca574b795f56e24644cbb67e661ab72b77a2e83ba3cf4ac3ae40f3ce4c5e4d2e016e8845e825dafee40179de1b9bab1a71c18aa82cca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
